version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./images:/home/sumer/Documents/Projects/Marketplace/images
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
